### ISSUE TITLE
Avoid double error messages

### ISSUE THREAD

**Issue by mlkersten** [MonetDBSolutions/monetdb-pystethoscope#26]
mk@toke::~/monetdb-pystethoscope> pystethoscope -d demo -i “pc statement”
Connected to the database: demo
Key pc statement not found in the JSON object
{}
Key pc statement not found in the JSON object
{}
Key pc statement not found in the JSON object

This message should only be given once, or terminate the process

**Comment by kutsurak** [comment]
I have started the implementation for this (it is a bit more involved than the other issues in the milestone) but I consider it to be a wrong move to have this as the only option:

In my opinion the repetition of the "key not found" message is useful because there are keys in the profiler object that are optional, i.e. can appear in some but not all of the objects in a query (better identification of the object in the error message is something that will be part of the solution). 

On the other hand if the user makes a typo it can be useful to make it obvious to them that there is a problem, and having a warning printed for every object makes it pretty obvious. Conversely, because stethoscope produces a lot of output if this is printed only once it will be easy for the user to miss.

By the way as things stand currently the users can redirect standard error to a file or to `/dev/null` and these messages will not appear at all on screen. 

I propose the following 2 remedies:
- better logging: Implementing a proper logging infrastructure with logging levels and components. (I will do this regardless of what we decide for this issue specifically).
- a "quiet" option: Maybe keep the default behavior as is currently and implement a "quiet" option that suppresses most error messages (or a "verbose" option that does the converse).

Let's take some time on Monday to discuss this.

**Comment by mlkersten** [comment]
i would simple keep a dictiorary of error messages and tally them. when you end the connection, you dump this dictionar
